[project]
name = "shapes"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numpy>=2.1.3",
    "pillow>=11.0.0",
    "pyside6>=6.8.0.2",
    "vispy>=0.14.3",
]
