[project]
name = "shapes"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numpy>=2.1.3",
    "pillow>=11.0.0",
    "pyopengl>=3.1.7",
    "vispy[pyside6]>=0.14.3",
]
